//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoPedido
    {
        public int idTipoPago { get; set; }
        public int idPedido { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
